### ISSUE TITLE
[REQUEST] Set different Radarr folder

### ISSUE THREAD

**Issue by michaelseth** [treysu/letterboxd-plex-sync#3]
First, thank you for your work! This is exactly what I've been looking for and it's amazing to see all my Letterboxd ratings in my Plex library.

I noticed when it tried to move to the Radarr part of things, I got this error message in Radarr: 

> -- RootFolderPath: Root folder '/movies' does not exist

I imagine it's set to add movies to a "movies" folder (which makes sense), however my setup is a little more complicated at the moment. Wondering if it would be possible to specify which directory to add the movies to in Radarr.

**Comment by treysu** [comment]
Hello, thank you for your interest in my tool! After [another issue](https://github.com/treysu/letterboxd-plex-sync/issues/2) was posted, I realized I had the Radarr integration essentially hardcoded to match my setup. I will be adding Environment variables to properly configure all aspects of Radarr soon.

**Comment by michaelseth** [comment]
🤦‍♂️ I totally should've checked the closed issues _before_ I posted. Thanks, though! It's truly the only tool that does _exactly_ what I wanted. The Radarr integration is a bonus.

**Comment by treysu** [comment]
@michaelseth No worries! That issue only covered a specific feature, and you shouldn't need to check closed issues for existing problems!

Please check the `treysu/letterboxd-plex-sync:dev` image. After I complete testing, I will merge to master.

New ENV Variables:
```
RADARR_ROOT_FOLDER='/movies'
RADARR_MONITORED='true'
RADARR_QUALITY_PROFILE='Bluray 4K Preferred'
```

**Comment by treysu** [comment]
This issue has been resolved in the most recent merge to `main`. Please set your image to `treysu/letterboxd-plex-sync:latest` and run `docker compose pull`, and refer to the [README ](https://github.com/treysu/letterboxd-plex-sync/blob/main/README.md)for how to use the new environment variables.
